export const setVisibilityFilter = filter => ({
    type: 'SET_VISIBILITY_FILTER',
    filter
  })

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_ORDER_FREQUENCY: 'SHOW_ORDER_FREQUENCY',
  SHOW_ORDER_LEVEL: 'SHOW_ORDER_LEVEL',
  SHOW_SEARCH_LEVEL: 'SHOW_SEARCH_LEVEL',
  SHOW_SEARCH_DESCRIPTION: 'SHOW_SEARCH_DESCRIPTION',
  SHOW_SEARCH_ORIGIN: 'SHOW_SEARCH_ORIGIN'

}
